import json, os
os.chdir('C:/Users/Augusto/Desktop/Programacion/campus-nika/campus-nika')
OUT = 'data/acreditaciones/sim/'
J = lambda p: json.load(open(p, encoding='utf8'))
W = lambda p, d: json.dump(d, open(p, 'w', encoding='utf8', newline=''), ensure_ascii=False, indent=1)
def dd(i, t, c, pq, tg, cl, **kw):
    o = dict(id=i, texto=t, critico=bool(c), porque=pq, target=tg, claves=cl); o.update(kw); return o
FA, FB, FC, FD, FE = 'Recepción y preparación', 'Inspección', 'Palpación', 'Educación y cierre', 'Cierre'
P = [
 (1, 'Saluda y se presenta', FA, 'paciente', 0, {'pres': 1}, 'hablar', 'Saludar y presentarse con nombre y rol genera confianza antes de un examen íntimo.',
  [['me presento'], ['soy la doctora'], ['soy el doctor'], ['buen dia'], ['buenas tardes'], ['mucho gusto']], 'Buenas tardes, soy la doctora, me presento con mi nombre y apellido.'),
 (2, 'Invita a sentarse a la paciente y al familiar', FA, 'consultorio', 0, {'sent': 1}, 'sentar', 'Se invita a sentarse a la paciente y a su acompañante para conversar antes del examen.',
  [['tome asiento'], ['tomar asiento'], ['siente'], ['sientese'], ['invito a sentarse']], 'Invito a sentarse a la paciente y a su familiar.'),
 (3, 'Inicia el interrogatorio y pregunta sobre antecedentes de patología mamaria', FA, 'paciente', 1, {'inter': 1}, 'preguntar', 'Se pregunta por dolor, nódulos, secreciones, cambios en la piel o el pezón, cirugías mamarias, uso de hormonas, lactancia, menarca, menopausia y antecedentes familiares de cáncer de mama y ovario.',
  [['interrogatorio'], ['antecedentes mamarios'], ['patologia mamaria'], ['antecedentes de patologia'], ['pregunto por antecedentes'], ['antecedentes de mama']], 'Inicio el interrogatorio y pregunto sobre antecedentes de patología mamaria.'),
 (4, 'Informa a la paciente y a su acompañante sobre el procedimiento que realizará para palpar las mamas y procede al lavado de manos', FA, 'manos', 1, {'info': 1, 'lav': 1}, 'lavado', 'Se explica en qué consiste el examen y que no debería doler, y se realiza el lavado de manos (con alcohol en gel o agua y jabón) antes de tocar a la paciente.',
  [['informo'], ['le explico'], ['lavado de manos'], ['me lavo las manos'], ['procedimiento para palpar']], 'Informo a la paciente y a su acompañante sobre el procedimiento para palpar las mamas y me lavo las manos.'),
 (5, 'Resguarda la intimidad y privacidad de la paciente: le indica que se coloque una bata y se ubique detrás del biombo', FA, 'biombo', 1, {'bata': 1}, 'biombo', 'Se resguarda el pudor de la paciente con una bata y un biombo, y solo se descubren las mamas durante el examen.',
  [['biombo'], ['bata'], ['resguardo la intimidad'], ['privacidad'], ['intimidad']], 'Resguardo su intimidad: le indico que se coloque una bata y se ubique detrás del biombo.'),
 (6, 'Invita a la paciente a sentarse con las manos en la cintura, descubrirse hasta la cintura y observa ambas mamas, el pezón y la areola', FB, 'mamas', 1, {'posA': 1}, 'postura_cintura', 'Con la paciente sentada, con las manos en la cintura (contrae los pectorales) y descubierta hasta la cintura, se comparan ambas mamas en simetría, forma y tamaño, y se observan el pezón y la areola.',
  [['manos en la cintura'], ['sentada'], ['descubrirse hasta la cintura'], ['observo ambas mamas'], ['observo las mamas']], 'La invito a sentarse con las manos en la cintura, descubrirse hasta la cintura y observo ambas mamas, el pezón y la areola.'),
 (7, 'En la misma posición, con los brazos en alto, inspecciona la región axilar y supraclavicular', FB, 'axila', 1, {'brazos': 1}, 'postura_brazos', 'Con los brazos en alto se evidencian retracciones y asimetrías que no se ven con los brazos abajo, y se inspeccionan las regiones axilares y supraclaviculares en busca de adenopatías.',
  [['brazos en alto'], ['region axilar'], ['supraclavicular'], ['inspecciono la axila'], ['levante los brazos']], 'Con los brazos en alto inspecciono la región axilar y supraclavicular.'),
 (8, 'Registra y observa su tamaño y conformación, prominencias o depresiones, edemas y procesos inflamatorios visibles en la superficie de la mama', FB, 'mamas', 1, {'tam': 1}, 'inspeccion_mama', 'Se registra el tamaño, la simetría, las prominencias o retracciones, el edema de la piel («piel de naranja») y los signos inflamatorios (eritema, calor).',
  [['tamano y conformacion'], ['prominencias'], ['depresiones'], ['edema'], ['piel de naranja'], ['procesos inflamatorios'], ['conformacion']], 'Registro y observo el tamaño y la conformación de las mamas, prominencias o depresiones, edemas y procesos inflamatorios visibles.'),
 (9, 'Identifica los cambios de pigmentación en el pezón, las areolas y las grietas', FB, 'areola', 0, {'pig': 1}, 'pigmentacion', 'Se observan el color de la areola y el pezón, las grietas, las erosiones y el eczema (enfermedad de Paget).',
  [['pigmentacion'], ['grietas'], ['color de la areola'], ['cambios de pigmentacion']], 'Identifico los cambios de pigmentación en el pezón y las areolas, y las grietas.'),
 (10, 'Reconoce la existencia de los tubérculos de Montgomery en la areola primaria y la red venosa de Haller en la superficie de la glándula mamaria', FB, 'areola', 0, {'mont': 1}, 'montgomery', 'Los tubérculos de Montgomery son glándulas sebáceas de la areola (se hacen prominentes en el embarazo); la red venosa de Haller es la red de venas subcutáneas, más visible en el embarazo o ante un tumor.',
  [['tuberculos de montgomery'], ['montgomery'], ['red venosa'], ['haller']], 'Reconozco los tubérculos de Montgomery en la areola primaria y la red venosa de Haller en la superficie de la glándula.'),
 (11, 'Le pide que se coloque en decúbito dorsal con las manos debajo de la región cervical y palpa cuidadosa y ordenadamente cada mama por cuadrantes, desde el pezón hacia la periferia y de regreso', FC, 'mamas', 1, {'palp': 1}, 'palpacion', 'En decúbito dorsal con las manos bajo la nuca se aplana la mama sobre el tórax. Con la palma y las yemas de los dedos se palpa cada cuadrante (superoexterno, superointerno, inferointerno e inferoexterno) desde el pezón hacia la periferia y de regreso, comparando ambas mamas y la prolongación axilar.',
  [['decubito dorsal'], ['palpo'], ['por cuadrantes'], ['cuadrantes'], ['palpacion de las mamas'], ['manos debajo de la nuca']], 'Le pido que se coloque en decúbito dorsal con las manos debajo de la nuca y palpo cuidadosa y ordenadamente cada mama por cuadrantes, desde el pezón a la periferia y de regreso.'),
 (12, 'Realiza la palpación de la areola y el pezón, presionando el pezón entre los dedos pulgar e índice', FC, 'pezon', 1, {'pezon': 1}, 'palpar_pezon', 'Se palpa la areola y se presiona suavemente el pezón entre el pulgar y el índice para evaluar su consistencia y expresar secreciones.',
  [['palpo la areola'], ['palpacion de la areola'], ['presiono el pezon'], ['entre el pulgar y el indice'], ['el pezon']], 'Palpo la areola y el pezón, presionando el pezón entre los dedos pulgar e índice.'),
 (13, 'Observa si al presionar existe algún tipo de secreción', FC, 'pezon', 1, {'secr': 1}, 'secrecion', 'Se observa el aspecto de la secreción: lechosa (galactorrea), serosa, serohemática o hemática (papiloma intraductal o neoplasia) o purulenta (infección). La secreción unilateral, espontánea y de un solo conducto exige estudio.',
  [['secrecion'], ['sale algo'], ['observo si hay'], ['expreso'], ['salida de liquido']], 'Observo si al presionar existe algún tipo de secreción.'),
 (14, 'Levanta el pezón junto con la areola para comprobar si hay buena movilidad o adherencia', FC, 'pezon', 1, {'movil': 1}, 'movilidad', 'Se eleva el complejo areola-pezón para evaluar su movilidad: la fijación o adherencia a planos profundos o la retracción sugieren una neoplasia subyacente.',
  [['levanto el pezon'], ['movilidad'], ['adherencia'], ['elevo el pezon'], ['levanto la areola']], 'Levanto el pezón junto con la areola para comprobar si hay buena movilidad o adherencia.'),
 (15, 'Enseña a la paciente a realizar el autoexamen de mamas', FD, 'autoexamen', 1, {'auto': 1}, 'autoexamen', 'Se enseña el autoexamen mensual (unos días después de la menstruación; en la posmenopausia, siempre el mismo día): frente al espejo y en decúbito, con la pulpa de los dedos, en círculos, en tiras verticales o en cuña, sin olvidar la axila y el pezón. Se consulta ante cualquier cambio.',
  [['autoexamen'], ['le ensenio'], ['le enseno'], ['como examinarse'], ['autoexploracion']], 'Le enseño a la paciente a realizar el autoexamen de mamas.'),
 (16, 'Invita a la paciente a vestirse', FD, 'paciente', 0, {'viste': 1}, 'vestirse', 'Se la invita a vestirse con privacidad y se la espera sentada para comentar los hallazgos.',
  [['vestirse'], ['se vista'], ['puede vestirse']], 'La invito a vestirse.'),
 (17, 'Escucha y responde las preguntas, preocupaciones y molestias de la paciente', FE, 'paciente', 0, {'preg': 1}, 'hablar', 'Se da espacio para dudas, se explican los hallazgos con claridad y se indican los estudios y controles (mamografía, ecografía mamaria).',
  [['preguntas'], ['dudas'], ['preocupaciones'], ['escucho'], ['molestias']], 'Escucho y respondo las preguntas, preocupaciones y molestias de la paciente.'),
 (18, 'Saluda y se despide', FE, 'paciente', 0, {'desp': 1}, 'hablar', 'El saludo final cierra la consulta.',
  [['me despido'], ['hasta luego'], ['hasta pronto'], ['chau']], 'Saludo y me despido de la paciente.'),
]
pasos = [dict(n=n, texto=tx, fase=fa, target=tg, critico=bool(cr), explica=ex, estado=es, claves=cl, frase=fr, fx=fx) for n, tx, fa, tg, cr, es, fx, ex, cl, fr in P]

def caso(i, nombre, edad, motivo, ant, lado, cuad, tam, nodtxt, piel, pezon, secr, adeno, ven, h_ant, h_insp, h_pig, h_mont, h_palp, h_pezon, h_secr, h_movil, h_axila, h_preg, extra, duro=False, bilateral=False, adherido=False):
    return dict(id=i, nombre=nombre, sexo='F', edad=edad, motivo=motivo, indicacion='Examen mamario.', antecedentes=ant, alergia=None, lado=lado, cuadrante=cuad, nod_tam=tam, nod_txt=nodtxt, nod_duro=duro, piel=piel, pezon=pezon, secrecion=secr, sec_bilateral=bilateral, adenopatia=adeno, venas=ven, adherido=adherido,
                h_ant=h_ant, h_insp=h_insp, h_pig=h_pig, h_mont=h_mont, h_palp=h_palp, h_pezon=h_pezon, h_secr=h_secr, h_movil=h_movil, h_axila=h_axila, h_preg=h_preg, extra=extra)
N = 'sin nódulos ni masas palpables'
casos = [
 caso('c1', 'Carolina M.', 25, 'Control mamario de rutina.', 'Sin antecedentes. Sin alergias conocidas.', 'D', 'CSE', 0, '', 'normal', 'normal', 'ninguna', False, False,
      'Refiere ciclos regulares, sin dolor ni nódulos; antecedente familiar de cáncer de mama en una tía materna.', 'Mamas simétricas, de tamaño y forma normales, sin retracciones ni cambios en la piel.', 'Areolas y pezones de color normal, sin grietas.', 'Tubérculos de Montgomery discretos; red venosa de Haller poco visible.',
      'Consistencia fibroglandular homogénea, sin nódulos ni masas en ninguno de los cuadrantes; sin dolor.', 'Pezones protráctiles, sin lesiones.', 'No hay secreción al presionar.', 'El complejo areola-pezón es móvil, sin adherencias.', 'Axilas y fosas supraclaviculares libres, sin adenopatías.', 'La paciente pregunta: «¿Con qué edad empiezo a hacerme la mamografía?».', ['Mama normal']),
 caso('c2', 'Lucía F.', 22, 'Noté una «bolita» en la mama derecha.', 'Sin antecedentes. Sin alergias conocidas.', 'D', 'CSE', 2, 'Nódulo de 2 cm, móvil y elástico', 'normal', 'normal', 'ninguna', False, False,
      'Refiere una «bolita» en la mama derecha hace 2 meses, que no duele ni cambió con la menstruación; sin antecedentes familiares.', 'Mamas simétricas, sin cambios en la piel ni retracciones.', 'Areola y pezón normales.', 'Tubérculos de Montgomery normales.',
      'En el cuadrante superoexterno de la mama derecha se palpa un nódulo de 2 cm, de bordes lisos y bien delimitados, de consistencia elástica y muy móvil («ratón de la mama»), indoloro; el resto sin alteraciones.', 'Pezón protráctil.', 'No hay secreción.', 'El complejo areola-pezón es móvil.', 'Axilas libres, sin adenopatías.', 'La paciente pregunta: «¿Es un cáncer? ¿Me lo tienen que sacar?».', ['Nódulo móvil']),
 caso('c3', 'Gladys R.', 58, 'Tengo una dureza en la mama izquierda y el pezón metido.', 'Menopausia a los 51 años. Terapia hormonal por 8 años. Madre con cáncer de mama. Sin alergias conocidas.', 'I', 'CSE', 3, 'Nódulo de 3 cm, duro, irregular y adherido', 'naranja', 'retraido', 'ninguna', True, True,
      'Refiere una masa dura en la mama izquierda hace 4 meses, con retracción del pezón y piel «como cáscara de naranja»; no consultó antes por miedo.', 'Asimetría: la mama izquierda tiene la piel engrosada con aspecto de «piel de naranja» y el pezón retraído.', 'Areola de color normal; pezón izquierdo retraído.', 'Red venosa de Haller prominente en la mama izquierda.',
      'En el cuadrante superoexterno de la mama izquierda se palpa una masa de 3 cm, dura, de bordes irregulares, indolora y adherida a planos profundos y a la piel.', 'Pezón izquierdo retraído e invertido.', 'No hay secreción.', 'El complejo areola-pezón está fijo, sin movilidad (adherido).', 'Adenopatías axilares izquierdas duras, fijas y de 2 cm.', 'La paciente pregunta: «¿Esto es grave? ¿Qué estudios necesito?».', ['Sospecha de cáncer de mama'], True, False, True),
 caso('c4', 'Marcela V.', 40, 'Dolor y bultos en ambas mamas antes de la menstruación.', 'Nuligesta. Sin alergias conocidas.', 'I', 'CSE', 1, 'Nodularidad difusa con quistes móviles', 'normal', 'normal', 'ninguna', False, False,
      'Refiere dolor y sensibilidad en ambas mamas los días previos a la menstruación, que mejoran luego del sangrado; cafeína abundante.', 'Mamas simétricas, sin cambios en la piel.', 'Areolas y pezones normales.', 'Tubérculos de Montgomery normales.',
      'Nodularidad difusa, de consistencia en «empedrado», más marcada en los cuadrantes superoexternos, con algún quiste móvil de 1 cm, doloroso a la palpación.', 'Pezones protráctiles.', 'No hay secreción.', 'El complejo areola-pezón es móvil.', 'Axilas libres.', 'La paciente pregunta: «¿Esto puede convertirse en cáncer?».', ['Mastopatía fibroquística']),
 caso('c5', 'Soledad A.', 30, 'Sale leche de mis pechos y no estoy amamantando.', 'Nuligesta. Amenorrea secundaria hace 6 meses. Sin alergias conocidas.', 'D', 'CSE', 0, '', 'normal', 'normal', 'lechosa', False, False,
      'Refiere salida espontánea de líquido blanquecino de ambas mamas y menstruaciones ausentes hace 6 meses; cefaleas.', 'Mamas simétricas, de tamaño normal, sin cambios en la piel.', 'Areolas y pezones normales.', 'Tubérculos de Montgomery normales.',
      'Mamas de consistencia fibroglandular, sin nódulos ni masas.', 'Pezones protráctiles.', 'Al presionar sale secreción lechosa, blanca, bilateral y por múltiples conductos (galactorrea).', 'El complejo areola-pezón es móvil.', 'Axilas libres.', 'La paciente pregunta: «¿Por qué sale leche si no estoy embarazada?».', ['Galactorrea'], False, True),
 caso('c6', 'Alicia P.', 45, 'Mancho el corpiño con sangre de la mama derecha.', 'G2P2. Sin alergias conocidas.', 'D', 'retroareolar', 0, '', 'normal', 'normal', 'hematica', False, False,
      'Refiere que desde hace un mes mancha el corpiño con una secreción sanguinolenta del pezón derecho, espontánea, sin dolor ni masa.', 'Mamas simétricas, sin cambios en la piel.', 'Areola y pezón derechos normales; mancha rojiza en el corpiño.', 'Tubérculos de Montgomery normales.',
      'No se palpan nódulos; un conducto retroareolar derecho se palpa levemente engrosado.', 'Pezón protráctil.', 'Al presionar sale secreción hemática por un solo conducto del pezón derecho (a las 10 horas).', 'El complejo areola-pezón es móvil.', 'Axilas libres.', 'La paciente pregunta: «¿Esa sangre es de un cáncer?».', ['Secreción hemática unilateral']),
 caso('c7', 'Natalia G.', 29, 'Dolor, calor y enrojecimiento en la mama izquierda; estoy amamantando.', 'Puérpera de 3 semanas, lactancia materna. Sin alergias conocidas.', 'I', 'CSE', 3, 'Zona indurada y dolorosa', 'eritema', 'normal', 'purulenta', False, True,
      'Refiere fiebre de 38,5 °C, escalofríos y dolor intenso en la mama izquierda desde hace 2 días, con grietas en el pezón.', 'Mama izquierda aumentada de tamaño, con eritema en cuña en el cuadrante superoexterno.', 'Pezón izquierdo con una grieta; areola congestiva.', 'Red venosa de Haller prominente (lactancia).',
      'En el cuadrante superoexterno izquierdo se palpa una zona indurada, caliente y muy dolorosa, sin fluctuación.', 'Pezón con grieta, erosionado.', 'Al presionar sale secreción láctea con algo de pus.', 'El complejo areola-pezón es móvil.', 'Adenopatía axilar izquierda dolorosa y móvil.', 'La paciente pregunta: «¿Puedo seguir amamantando?».', ['Mastitis lactacional']),
]
for c in casos[:2]: c['venas'] = False
dists = [
 dd('d1', 'Palpa las mamas sin haberlas inspeccionado antes', 1, 'Es criterio de desaprobación: la inspección (con las manos en la cintura y con los brazos en alto) precede a la palpación y detecta retracciones y asimetrías.', 'mamas', [['sin inspeccionar'], ['sin observar antes'], ['palpo sin mirar'], ['omito la inspeccion']]),
 dd('d2', 'Palpa solo la mama que le preocupa a la paciente', 1, 'Es criterio de desaprobación: se examinan siempre ambas mamas y las axilas, comparándolas.', 'mamas', [['solo la mama derecha'], ['solo la mama izquierda'], ['solo la que le duele'], ['solo una mama'], ['solo la afectada']]),
 dd('d3', 'Palpa los cuadrantes sin orden ni sistema', 1, 'Es criterio de desaprobación: se palpa cuidadosa y ordenadamente por cuadrantes, desde el pezón a la periferia y de regreso.', 'mamas', [['sin orden'], ['al azar'], ['sin sistema'], ['palpo cualquier lugar'], ['sin seguir un orden']]),
 dd('d4', 'Omite la exploración de las axilas y las fosas supraclaviculares', 1, 'Es criterio de desaprobación: las adenopatías axilares y supraclaviculares orientan la extensión de la enfermedad.', 'axila', [['sin explorar la axila'], ['omito la axila'], ['no exploro la axila'], ['no reviso las axilas'], ['sin axilas']]),
 dd('d5', 'No resguarda la intimidad de la paciente', 1, 'Es criterio de desaprobación: se utiliza bata y biombo y solo se descubren las mamas durante el examen.', 'biombo', [['sin bata'], ['sin biombo'], ['no resguardo'], ['delante de todos']]),
 dd('d6', 'Presiona o comprime la mama con fuerza excesiva o con las uñas', 0, 'La palpación se hace con la palma y las yemas de los dedos, con presión graduada, sin pellizcar ni usar las uñas.', 'mamas', [['con fuerza excesiva'], ['pellizco'], ['con las unas'], ['aprieto fuerte'], ['con brusquedad']]),
 dd('d7', 'Indica a la paciente que no hace falta hacerse el autoexamen ni consultar ante cambios', 1, 'Es criterio de desaprobación: se debe enseñar el autoexamen y la consulta ante cualquier cambio.', 'autoexamen', [['no hace falta el autoexamen'], ['no necesita el autoexamen'], ['no se examine'], ['no hace falta consultar']]),
 dd('d8', 'Omite la presión del pezón para ver si hay secreción', 1, 'Es criterio de desaprobación: la secreción es un dato clave (hemática, serosa, lechosa o purulenta).', 'pezon', [['sin presionar el pezon'], ['no presiono el pezon'], ['omito el pezon'], ['sin expresar']]),
 dd('d9', 'Palpa con la paciente sentada sin extender el brazo o sin posición adecuada, descartando el decúbito', 0, 'Para la palpación se coloca a la paciente en decúbito dorsal con las manos bajo la nuca, aplanando la mama sobre el tórax.', 'mamas', [['sentada para palpar'], ['de pie para palpar'], ['sin decubito']]),
 dd('d10', 'No se lava las manos antes de examinar', 1, 'Es criterio de desaprobación: la higiene de manos es obligatoria antes de tocar a la paciente.', 'manos', [['sin lavarme'], ['no me lavo las manos'], ['sin lavado de manos'], ['omito el lavado']]),
]
QS = [
 ('¿En qué posición se inspeccionan las mamas?', ['Sentada, con las manos en la cintura y luego con los brazos en alto', 'Acostada boca abajo', 'De pie con los brazos cruzados', 'Solo acostada'], 0, 'La inspección en esas dos posiciones evidencia retracciones y asimetrías.'),
 ('¿En qué posición se palpan las mamas?', ['Decúbito dorsal con las manos bajo la nuca', 'Sentada con los brazos en alto', 'De pie', 'Decúbito lateral'], 0, 'Aplana la mama sobre el tórax y facilita la palpación.'),
 ('¿Cómo se palpa cada mama?', ['Por cuadrantes, desde el pezón a la periferia y de regreso', 'Solo el cuadrante dolorido', 'Con un pellizco general', 'Solo el centro'], 0, 'Palpación ordenada por cuadrantes, con palma y yemas de los dedos.'),
 ('¿Cuáles son los cuadrantes de la mama?', ['Superoexterno, superointerno, inferoexterno e inferointerno (más la prolongación axilar)', 'Anterior, posterior, derecho e izquierdo', 'Solo superior e inferior', 'Cuatro cuadrantes de la areola'], 0, 'El cuadrante superoexterno es el más frecuente de tumores por su mayor cantidad de glándula.'),
 ('¿Qué son los tubérculos de Montgomery?', ['Glándulas sebáceas de la areola', 'Ganglios axilares', 'Quistes del pezón', 'Venas superficiales'], 0, 'Se hacen más prominentes durante el embarazo.'),
 ('¿Qué es la red venosa de Haller?', ['La red de venas subcutáneas de la mama', 'Los conductos galactóforos', 'Un ligamento de Cooper', 'Un ganglio'], 0, 'Se vuelve más visible en el embarazo, la lactancia o ante un tumor.'),
 ('Un nódulo duro, irregular, adherido y con retracción del pezón sugiere...', ['Cáncer de mama', 'Fibroadenoma', 'Mastopatía fibroquística', 'Mastitis'], 0, 'Son signos de malignidad: requiere mamografía, ecografía y biopsia.'),
 ('Un nódulo liso, móvil y elástico en una mujer joven sugiere...', ['Fibroadenoma', 'Cáncer', 'Absceso', 'Galactorrea'], 0, 'El fibroadenoma es el tumor benigno más frecuente en mujeres jóvenes.'),
 ('Una secreción hemática unilateral por un solo conducto sugiere...', ['Papiloma intraductal (o neoplasia): requiere estudio', 'Embarazo', 'Galactorrea', 'Es normal'], 0, 'La secreción espontánea unilateral de un solo conducto exige estudio.'),
 ('Una secreción lechosa bilateral fuera de la lactancia se llama...', ['Galactorrea (descartar hiperprolactinemia)', 'Telorrea', 'Mastalgia', 'Mastitis'], 0, 'Se estudia la prolactina, la TSH y los fármacos.'),
 ('¿Cuándo se recomienda hacerse el autoexamen mamario?', ['Una vez por mes, unos días después de la menstruación', 'Una vez por año', 'Solo si duele', 'Nunca'], 0, 'En la posmenopausia, siempre el mismo día de cada mes.'),
 ('Fijación del pezón y de la areola a planos profundos sugiere...', ['Neoplasia subyacente', 'Embarazo', 'Mastitis', 'Normalidad'], 0, 'La movilidad conservada del complejo areola-pezón es normal.'),
]
fund = [dict(q=q, o=o, c=c, e=e) for q, o, c, e in QS]
mach = {'perlas': [
 {'t': 'Antes del examen', 'x': 'Saludá, sentá a la paciente y al familiar, interrogá antecedentes mamarios, informá, lavate las manos y resguardá su intimidad (bata y biombo).'},
 {'t': 'Inspección', 'x': 'Sentada con las manos en la cintura: simetría, tamaño, piel, pezón y areola. Con los brazos en alto: retracciones, axila y región supraclavicular. Anotá edema, inflamación, pigmentación, grietas, tubérculos de Montgomery y red de Haller.'},
 {'t': 'Palpación', 'x': 'Decúbito dorsal, manos bajo la nuca. Palma y yemas, por cuadrantes del pezón a la periferia y de regreso, en ambas mamas, más axila.'},
 {'t': 'Pezón', 'x': 'Palpá la areola, presioná el pezón entre pulgar e índice (¿secreción?: lechosa, serosa, hemática, purulenta) y elevalo con la areola (¿móvil o adherido?).'},
 {'t': 'Cierre', 'x': 'Enseñá el autoexamen, dejá que se vista, respondé dudas y despedite.'}], 'por_paso': {'6': 'Manos en la cintura.', '7': 'Brazos en alto + axila y supraclavicular.', '11': 'Decúbito, manos bajo la nuca.', '12': 'Pezón entre pulgar e índice.', '15': 'Autoexamen mensual.'}}
CRIT = dict(criterios_texto='La lista de cotejo no define criterios de desaprobación automática; el simulador califica la información y la intimidad, la inspección en dos posiciones, la palpación ordenada por cuadrantes de ambas mamas, la exploración del pezón y la axila y la enseñanza del autoexamen (propuesto, a validar).',
  criterios=[dict(ico='🛡️', titulo='Información, lavado de manos e intimidad', pasos=[4, 5]), dict(ico='👁️', titulo='Inspección en dos posiciones, axila y supraclavicular', pasos=[6, 7, 8]), dict(ico='🖐️', titulo='Palpación ordenada por cuadrantes', pasos=[11]), dict(ico='💧', titulo='Pezón: secreción y movilidad', pasos=[12, 13, 14]), dict(ico='🪞', titulo='Enseñanza del autoexamen', pasos=[15])],
  final_criticos='la información e intimidad, la inspección, la palpación por cuadrantes, el examen del pezón y el autoexamen')
ALG = dict(titulo='Hallazgos del examen mamario', boton_titulo='Ver los hallazgos típicos', boton_sub='Benigno, inflamatorio y sospechoso', aviso='los hallazgos típicos', flecha='▼ Características del nódulo', flecha_final='▼ Conducta', pie='Todo hallazgo sospechoso se completa con mamografía/ecografía y biopsia.',
 comun=[dict(t='Inspección', x='Simetría, piel, pezón, areola, axila.', flag='tam'), dict(t='Palpación', x='Cuadrantes, areola, pezón y axila.', flag='palp')],
 columnas=[dict(titulo='Benigno', cls='nd', nodos=[dict(t='Fibroadenoma', x='Liso, móvil, elástico, indoloro; mujer joven.', flag='palp'), dict(t='Mastopatía fibroquística', x='Nodularidad difusa y dolor premenstrual.', flag='palp'), dict(t='Galactorrea', x='Secreción lechosa bilateral: estudiar prolactina.', flag='secr')]),
  dict(titulo='Inflamatorio', cls='fv', nodos=[dict(t='Mastitis', x='Calor, rubor, dolor, fiebre; lactancia.', flag='tam'), dict(t='Absceso', x='Colección fluctuante: drenaje.', flag='palp')]),
  dict(titulo='Sospechoso de malignidad', cls='fv', nodos=[dict(t='Nódulo duro e irregular', x='Adherido, con piel de naranja o retracción del pezón.', flag='palp'), dict(t='Adenopatías axilares', x='Duras y fijas.', flag='brazos'), dict(t='Secreción hemática unilateral', x='Un solo conducto.', flag='secr')])],
 final=[dict(t='Estudios', x='Mamografía, ecografía mamaria y biopsia.', flag='palp'), dict(t='Autoexamen', x='Mensual, con ayuda del espejo y en decúbito.', flag='auto')])
EL = {'paciente': ('Paciente', 'Se la saluda, se resguarda su intimidad y se la despide.'), 'consultorio': ('Consultorio', 'Sillas para la paciente y el acompañante.'), 'manos': ('Manos', 'Lavado de manos antes de examinar.'), 'biombo': ('Biombo y bata', 'Resguardan la intimidad.'),
      'mamas': ('Mamas', 'Se inspeccionan, comparan y palpan.'), 'axila': ('Región axilar y supraclavicular', 'Se inspecciona y se palpa.'), 'areola': ('Areola y pezón', 'Pigmentación, tubérculos de Montgomery y red de Haller.'), 'pezon': ('Pezón', 'Se presiona y se eleva.'), 'autoexamen': ('Autoexamen', 'Se enseña a la paciente.')}
EX = dict(id='exmam', area='sim', titulo='Examen mamario', icono='🎀',
 resumen='Recorrido virtual del examen mamario con 18 pasos de la lista de cotejo: inspección en dos posiciones, palpación por cuadrantes de ambas mamas, examen del pezón y la axila, y enseñanza del autoexamen, con casos benignos, inflamatorios y sospechosos.',
 umbral=60, fuente='Lista de cotejo: Examen mamario (18 ítems)', elementos={k: dict(nombre=v[0], desc=v[1], pasos=[p['n'] for p in pasos if p['target'] == k]) for k, v in EL.items()},
 distractores=dists, casos=casos, fundamentos=fund, voz=True, algoritmo=ALG,
 hallazgo_pasos={'3': 'h_ant', '7': 'h_axila', '8': 'h_insp', '9': 'h_pig', '10': 'h_mont', '11': 'h_palp', '12': 'h_pezon', '13': 'h_secr', '14': 'h_movil', '17': 'h_preg'},
 hallazgo_rotulos={'3': '🗣 Paciente:', '7': '👁️ Observás:', '8': '👁️ Observás:', '9': '👁️ Observás:', '10': '👁️ Observás:', '11': '🖐️ Palpás:', '12': '🖐️ Palpás:', '13': '💧 Observás:', '14': '🖐️ Palpás:', '17': '🗣 Paciente:'}, hallazgo_voz={'3': 'f', '17': 'f'},
 machete=mach, examen=dict(tiempos=[5, 10, 15, 30], penalizacion_incorrecta=3, penalizacion_repetida=1),
 visor='data/acreditaciones/sim/exmam_modelo.json', peso_modelo='2 MB', instrumental='data/acreditaciones/sim/instrumental_exmam.json', mesa_pasos=[], pasos=pasos)
EX.update(CRIT); W(OUT + 'exmam.json', EX)
def it(id, grupo, nombre, detalle, correcto, critico, desc, ficha, **kw):
    o = dict(id=id, grupo=grupo, nombre=nombre, detalle=detalle, img=f'assets/instrumental/{id}.svg', correcto=correcto, critico=critico, descripcion=desc, ficha=ficha); o.update(kw); return o
items = [
 it('bata_paciente', 'prot', 'Bata de la paciente', 'Descartable', True, True, 'Para que la paciente se descubra resguardando su pudor.', [['Uso', 'Intimidad']], falta='Falta la bata para la paciente.'),
 it('biombo', 'prot', 'Biombo', 'Plegable', True, True, 'Para que la paciente se cambie con privacidad.', [['Uso', 'Privacidad']], falta='Falta el biombo para resguardar la intimidad.'),
 it('alcohol_gel', 'prot', 'Alcohol en gel', 'Higiene de manos', True, True, 'Higiene de manos antes de examinar.', [['Uso', 'Higiene']], falta='Falta el alcohol en gel para la higiene de manos.'),
 it('camilla_obs', 'prot', 'Camilla', 'Con almohada', True, True, 'Para el decúbito dorsal en la palpación.', [['Uso', 'Decúbito']], falta='Falta la camilla para la palpación en decúbito.'),
 it('guia_autoexamen', 'educ', 'Guía del autoexamen mamario', 'Folleto ilustrado', True, False, 'Material para enseñar el autoexamen a la paciente.', [['Uso', 'Educación']], opcional=True),
 it('mamografo', 'otros', 'Mamógrafo', 'Equipo de rayos X', False, False, 'Estudio por imágenes.', [['Uso', 'Mamografía']], feedback='La mamografía es un estudio complementario; no forma parte del examen clínico.'),
 it('gel_ecografia', 'otros', 'Gel conductor para ecografía', 'Frasco', False, False, 'Para ecografía.', [['Uso', 'Ecografía']], feedback='La ecografía mamaria se indica después del examen clínico.'),
 it('aguja', 'otros', 'Jeringa y aguja para punción', 'Estéril', False, False, 'Punción aspirativa.', [['Uso', 'PAAF']], feedback='La punción se indica según los hallazgos, no en el examen clínico de rutina.'),
]
INS = dict(id='exmam', titulo='Consultorio de mastología · Examen mamario', consigna='Preparás el consultorio para el examen mamario: privacidad, higiene, camilla y material educativo. Pasá el cursor (o tocá) cada insumo para inspeccionarlo; arrastralo a la bandeja o hacé clic para agregarlo.',
 caso_sub='examen mamario', indicacion_def='Examen mamario.', mision=['qué hace falta para examinar con privacidad e higiene;', 'qué estudios o insumos no corresponden al examen clínico.'], demo_caso='Primero se lee el caso: el motivo orienta qué buscar en la inspección y en la palpación.',
 grupos=[dict(id='prot', titulo='Privacidad e higiene'), dict(id='educ', titulo='Educación'), dict(id='otros', titulo='Otros insumos')], items=items, bandeja_img='assets/instrumental/bandeja.svg')
W(OUT + 'instrumental_exmam.json', INS)
M = J('data/acreditaciones/siam/sv_modelo.json')
glb = lambda id, carpeta, f, capa, color, op, hs, nom, peso, **kw: dict(id=id, tipo='glb', src=f'assets/anatomia/{carpeta}/{f}.glb', escala=100, rot=[0, 0, 0], pos=[0, 0, 0], capa=capa, color=color, opacidad=op, hs=hs, nombre=nom, peso=peso, **kw)
piezas = [glb('piel', 'sim', 'torso_f', 'piel', '#d8a387', 0.30, None, 'Paciente', 1255052, piel_real=True)]
VAR = dict(origen=[0, 39, 6], corte_x=0.0, rotacion=[0, 0, 0], piezas=piezas, procedurales={},
  mam=dict(pezon_d=[-10.6, 39.3, 8.6], pezon_i=[9.4, 39.3, 8.6], R=7.5, th=0.95),
  pines=dict(pezonD=[-10.6, 39.3, 9.2], pezonI=[9.4, 39.3, 9.2], axila=[-17, 44, 0]),
  camara=dict(lat=[70, 40, 0], fro=[0, 40, 70], sup=[0.01, 80, 6], objetivo=[0, 1, 0], ini=[8, 6, 44]), etiquetas=dict(pezonD=[-110, 40], pezonI=[110, 40]))
G = dict(M['general']); G['camara'] = dict(M['general']['camara'], foco=28, min=10, max=120)
IM = dict(general=G, overlay_html='', tarjetas=dict(mesa=dict(titulo='🧰 Consultorio', id='mesa', items=[['manos', '🫧', 'Higiene', 'de manos'], ['biombo', '🪟', 'Biombo', 'y bata'], ['autoexamen', '🪞', 'Guía del', 'autoexamen']]), entorno=dict(titulo='🏥 Examen', items=[['paciente', '🧍‍♀️', 'Paciente', ''], ['mamas', '🎀', 'Mamas', ''], ['axila', '💪', 'Axila', ''], ['areola', '⭕', 'Areola', 'y pezón']])),
  chips=[['posA', 'Manos en la cintura'], ['brazos', 'Brazos en alto'], ['tam', 'Inspección'], ['palp', 'Palpación'], ['pezon', 'Pezón'], ['secr', 'Secreción'], ['auto', 'Autoexamen']],
  usables=['manos', 'biombo', 'autoexamen', 'paciente', 'mamas', 'axila', 'areola', 'pezon'], pines=[dict(id='pezonD', label='Mama derecha', capa='piel', externo=True), dict(id='pezonI', label='Mama izquierda', capa='piel', externo=True)],
  instrumentos=[dict(id='mam', tipo='mam', clases=dict(posA='s-posA', brazos='s-brazos', tam='s-tam', palp='s-palp', pezon='s-pezon', secr='s-secr', movil='s-movil', auto='s-auto'))], M=VAR, F=VAR)
W(OUT + 'exmam_modelo.json', IM)
print('ok exmam', len(pasos), len(casos))
