import json, os
os.chdir('C:/Users/Augusto/Desktop/Programacion/campus-nika/campus-nika')
OUT = 'data/acreditaciones/sim/'
J = lambda p: json.load(open(p, encoding='utf8'))
W = lambda p, d: json.dump(d, open(p, 'w', encoding='utf8', newline=''), ensure_ascii=False, indent=1)
def dd(i, t, c, pq, tg, cl, **kw):
    o = dict(id=i, texto=t, critico=bool(c), porque=pq, target=tg, claves=cl); o.update(kw); return o
FA, FB, FC, FD, FE, FF = 'Recepción y preparación', 'Examen de genitales externos', 'Examen con espéculo y toma de PAP', 'Tacto vaginal bimanual', 'Finalización', 'Cierre'
# (n, texto, fase, target, crítico, estado, fx, explica, claves, frase)
P = [
 (1, 'Saluda y se presenta', FA, 'paciente', 0, {'pres': 1}, 'hablar', 'Se saluda con respeto y se dice el nombre y el rol antes del examen: un examen ginecológico es íntimo y requiere confianza.',
  [['me presento'], ['soy la doctora'], ['soy el doctor'], ['buen dia'], ['buenas tardes'], ['mucho gusto']], 'Buenas tardes, soy la doctora, me presento con mi nombre y apellido.'),
 (2, 'Invita a sentarse a la paciente y al familiar', FA, 'consultorio', 0, {'sent': 1}, 'sentar', 'Se invita a sentarse a la paciente y a su acompañante para conversar antes del examen.',
  [['tome asiento'], ['tomar asiento'], ['siente'], ['sientese'], ['invito a sentarse']], 'Invito a sentarse a la paciente y a su familiar.'),
 (3, 'Inicia el interrogatorio y pregunta por antecedentes de patología ginecológica', FA, 'paciente', 0, {'inter': 1}, 'preguntar', 'Se interroga sobre síntomas, ciclos, FUM, antecedentes de ITS, PAP previos y cirugías ginecológicas.',
  [['interrogatorio'], ['antecedentes ginecologicos'], ['patologia ginecologica'], ['antecedentes de patologia'], ['pregunto por antecedentes']], 'Inicio el interrogatorio y pregunto por antecedentes de patología ginecológica.'),
 (4, 'Informa a la paciente y a su acompañante sobre el procedimiento que realizará', FA, 'paciente', 1, {'info': 1}, 'hablar', 'Se explica qué se va a hacer (examen de genitales, espéculo, toma de PAP y tacto), para qué sirve y que puede sentir presión pero no debería doler. Informar y obtener la aceptación es parte del acto médico.',
  [['informo'], ['le explico'], ['explico el procedimiento'], ['voy a realizar'], ['procedimiento que realizare']], 'Informo a la paciente y a su acompañante sobre el procedimiento que realizaré: examen de los genitales, toma de PAP y tacto vaginal.'),
 (5, 'Invita e indica cómo colocarse en posición ginecológica', FA, 'camilla', 0, {'pos': 1}, 'posicion_gin', 'Posición ginecológica (litotomía): decúbito dorsal con las rodillas flexionadas, los muslos separados y los talones en los estribos; la pelvis al borde de la camilla.',
  [['posicion ginecologica'], ['litotomia'], ['estribos'], ['colocarse en posicion'], ['se coloque en posicion']], 'La invito y le indico cómo colocarse en posición ginecológica.'),
 (6, 'Cubre a la paciente resguardando su intimidad y le pide que se libere de la ropa, incluida la interior', FA, 'sabana', 1, {'cubre': 1}, 'sabana', 'Se cubre a la paciente con una sábana o bata y solo se descubre la zona del examen: se resguarda su intimidad y su pudor.',
  [['resguardo su intimidad'], ['la cubro'], ['sabana'], ['intimidad'], ['ropa interior'], ['bata']], 'La cubro con una sábana resguardando su intimidad y le pido que se libere de la ropa, incluida la interior.'),
 (7, 'Utiliza guantes de látex y luz', FB, 'guantes', 1, {'guantes': 1}, 'guante_luz', 'Se colocan guantes de látex (barrera de protección) y se enciende la lámpara de pie orientándola hacia el introito para ver bien.',
  [['guantes'], ['lampara'], ['luz'], ['me coloco los guantes']], 'Me coloco los guantes de látex y enciendo la luz, orientándola hacia el introito.'),
 (8, 'Observa y reconoce los genitales externos', FB, 'vulva', 1, {'vulva': 1}, 'observar_genitales', 'Se inspeccionan el monte de Venus, los labios mayores y menores, el clítoris, el meato uretral, el introito y la horquilla, buscando lesiones, secreciones, tumoraciones, vello, signos de atrofia o inflamación.',
  [['genitales externos'], ['observo la vulva'], ['monte de venus'], ['labios mayores'], ['reconozco los genitales'], ['inspecciono']], 'Observo y reconozco los genitales externos: monte de Venus, labios, clítoris, meato y horquilla.'),
 (9, 'Entreabre la vulva a la altura del introito con los dedos índice y pulgar de la mano hábil', FB, 'vulva', 1, {'abre': 1}, 'entreabrir', 'Con el índice y el pulgar de la mano hábil se separan los labios menores a nivel del introito, lo que deja ver el vestíbulo y el orificio vaginal y facilita la introducción del espéculo.',
  [['entreabro la vulva'], ['entreabro'], ['separo los labios'], ['abro la vulva'], ['indice y pulgar de la mano habil']], 'Entreabro la vulva a la altura del introito con los dedos índice y pulgar de la mano hábil.'),
 (10, 'Introduce el espéculo cerrado con la articulación hacia abajo, apoyándolo sobre la horquilla, ligeramente inclinado hacia la izquierda, y lo rota 90° en sentido horario a medida que avanza', FC, 'especulo', 1, {'esp': 1}, 'esp_insertar', 'El espéculo cerrado y sin lubricante (solo agua tibia) se apoya sobre la horquilla, con la articulación hacia abajo y algo inclinado hacia la izquierda; al avanzar se lo rota 90° en sentido horario para que las valvas queden en posición superior e inferior, siguiendo el eje de la vagina (hacia el sacro).',
  [['introduzco el especulo'], ['introduzco', 'especulo'], ['especulo cerrado'], ['rotandolo 90'], ['rota 90'], ['inserto el especulo']], 'Introduzco el espéculo cerrado con la articulación hacia abajo, apoyado sobre la horquilla, inclinado hacia la izquierda, y lo roto 90° en sentido horario a medida que avanza.'),
 (11, 'Mantiene el espéculo en posición presionando la valva superior con el pulgar de la mano izquierda y separa las valvas', FC, 'especulo', 1, {'valvas': 1}, 'esp_abrir', 'Se sostiene el espéculo con la mano izquierda, se presiona con el pulgar la palanca de la valva superior para separar las valvas y se fija el tornillo en posición abierta, dejando a la vista el cuello uterino.',
  [['separo las valvas'], ['abro las valvas'], ['valva superior'], ['separa las valvas'], ['abro el especulo'], ['presionando la valva']], 'Mantengo el espéculo en posición, presiono la valva superior con el pulgar de la mano izquierda y separo las valvas.'),
 (12, 'Ubica y reconoce el cuello uterino', FC, 'cuello', 1, {'cuello': 1}, 'ubicar_cuello', 'Se identifica el cuello uterino y se describe: color, tamaño, forma del orificio externo (puntiforme en la nulípara y en hendidura en la multípara), secreciones, lesiones o sangrado.',
  [['ubico el cuello'], ['reconozco el cuello'], ['cuello uterino'], ['localizo el cuello'], ['identifico el cuello']], 'Ubico y reconozco el cuello uterino.'),
 (13, 'Toma la muestra del exocérvix con espátula de Ayre y extiende el material en el portaobjetos', FC, 'espatula', 1, {'ayre': 1}, 'toma_exo', 'Se apoya la espátula de Ayre con la punta larga en el orificio cervical y se gira 360° apoyando el borde sobre el exocérvix; el material se extiende en una sola capa fina sobre el portaobjetos rotulado.',
  [['espatula de ayre'], ['exocervix'], ['ectocervix'], ['toma exocervical'], ['ayre']], 'Tomo la muestra del exocérvix con la espátula de Ayre y extiendo el material en el portaobjetos.'),
 (14, 'Toma la muestra del endocérvix con citobrush y extiende el material en otro portaobjetos', FC, 'citobrush', 1, {'cito': 1}, 'toma_endo', 'Se introduce el cepillo (citobrush) en el canal endocervical y se lo gira un cuarto a media vuelta; el material se extiende en otro portaobjetos con un solo movimiento.',
  [['citobrush'], ['endocervix'], ['toma endocervical'], ['cepillo']], 'Tomo la muestra del endocérvix con el citobrush y extiendo el material en otro portaobjetos.'),
 (15, 'Fija las muestras con spray', FC, 'fijador', 1, {'fija': 1}, 'fijar_spray', 'Los extendidos se fijan de inmediato con spray fijador a 20-30 cm: si se secan al aire se alteran las células y el PAP no es interpretable.',
  [['fijo'], ['spray'], ['fijador'], ['fijar las muestras']], 'Fijo las muestras con spray fijador.'),
 (16, 'Cierra el espéculo y lo retira de la vagina', FC, 'especulo', 1, {'cierra': 1, 'retira': 1}, 'esp_retirar', 'Se afloja el tornillo, se cierran las valvas parcialmente y se retira el espéculo lentamente, rotándolo, sin pellizcar la mucosa ni los labios.',
  [['cierro el especulo'], ['retiro el especulo'], ['cierro y retiro'], ['saco el especulo']], 'Cierro el espéculo y lo retiro de la vagina.'),
 (17, 'Explica a la paciente que procederá a realizar el tacto vaginal bimanual', FD, 'paciente', 0, {'expl2': 1}, 'hablar', 'Se avisa lo que se va a hacer (tacto con dos dedos y la otra mano sobre el abdomen) para evitar sorpresas y contracturas.',
  [['tacto vaginal bimanual'], ['tacto bimanual'], ['voy a hacer el tacto'], ['procedere a realizar el tacto']], 'Le explico que procederé a realizar el tacto vaginal bimanual.'),
 (18, 'Entreabre la vulva a la altura del introito con los dedos índice y pulgar de la mano que no realizará el tacto (mano menos hábil)', FD, 'vulva', 0, {'abre2': 1}, 'entreabrir', 'Con la mano menos hábil se separan los labios para que la mano examinadora entre sin tocar el vello ni la piel.',
  [['mano menos habil'], ['entreabro', 'menos habil'], ['entreabro la vulva con la mano que no'], ['mano que no realizara']], 'Entreabro la vulva con los dedos índice y pulgar de la mano menos hábil, la que no realizará el tacto.'),
 (19, 'Introduce el dedo medio de la mano hábil apoyándolo sobre la horquilla, presiona en dirección al sacro y luego hace penetrar el índice recorriendo la vagina en toda su longitud', FD, 'dedos', 1, {'bimd': 1}, 'tacto_dedos', 'Se introduce el dedo medio apoyado en la horquilla vulvar presionando hacia el sacro (relaja el músculo) y luego el índice, y se recorre la vagina en toda su longitud: paredes, fondos de saco y cuello (consistencia, forma y dolor a la movilización).',
  [['dedo medio'], ['introduzco el dedo'], ['recorro la vagina'], ['hacia el sacro'], ['dedos en la vagina']], 'Introduzco el dedo medio de la mano hábil apoyado en la horquilla, presiono hacia el sacro, hago penetrar el índice y recorro la vagina en toda su longitud.'),
 (20, 'Aplica la mano libre sobre el hipogastrio y luego sobre ambas fosas ilíacas, presionando suavemente y abarcando con ambas manos los diversos órganos', FD, 'hipogastrio', 1, {'bima': 1}, 'tacto_abdomen', 'La mano libre se apoya sobre el hipogastrio y luego sobre cada fosa ilíaca, presionando suavemente hacia los dedos vaginales: se palpa el útero (tamaño, forma, consistencia, movilidad, dolor) y los anexos.',
  [['mano libre'], ['hipogastrio'], ['fosas iliacas'], ['abarco con ambas manos'], ['palpo el utero']], 'Aplico la mano libre sobre el hipogastrio y luego sobre ambas fosas ilíacas, presionando suavemente y abarcando los órganos con ambas manos.'),
 (21, 'Retira suavemente la mano examinadora de la vagina', FD, 'dedos', 0, {'bimr': 1}, 'retirar_mano', 'Los dedos se retiran lentamente, sin molestias, y se revisa el guante (sangre, secreciones).',
  [['retiro la mano'], ['retiro suavemente'], ['retiro los dedos']], 'Retiro suavemente la mano examinadora de la vagina.'),
 (22, 'Descarta el material descartable y los guantes', FE, 'residuos', 1, {'desc': 1}, 'residuos', 'El espéculo descartable y los guantes se descartan en la bolsa roja de residuos patogénicos; los portaobjetos fijados se guardan para el laboratorio; se realiza higiene de manos.',
  [['descarto'], ['desecho'], ['guantes'], ['bolsa roja'], ['material descartable']], 'Descarto el material descartable y los guantes en la bolsa roja.'),
 (23, 'Comunica a la paciente que finalizó el examen y le indica que se vista y tome asiento', FE, 'paciente', 0, {'fin': 1}, 'vestirse', 'Se avisa que terminó, se resguarda la intimidad mientras se viste y se la invita a sentarse para conversar.',
  [['finalizo el examen'], ['termino el examen'], ['se vista'], ['tome asiento'], ['hemos terminado']], 'Le comunico que finalizó el examen y le indico que se vista y tome asiento.'),
 (24, 'Escucha y responde a las preguntas, preocupaciones y molestias de la paciente', FE, 'paciente', 0, {'preg': 1}, 'hablar', 'Se da espacio para dudas, se explican los hallazgos con lenguaje claro y se contiene a la paciente.',
  [['preguntas'], ['dudas'], ['preocupaciones'], ['escucho'], ['molestias']], 'Escucho y respondo a las preguntas, preocupaciones y molestias de la paciente.'),
 (25, 'Le indica cómo retirar el resultado del PAP', FF, 'resultado', 0, {'res': 1}, 'resultado_pap', 'Se indica dónde y cuándo retirar el resultado (por ejemplo en 15 a 30 días en el laboratorio o en el centro de salud) y que debe traerlo a la consulta.',
  [['retirar el resultado'], ['retirar los resultados'], ['resultado del pap'], ['resultado del papanicolau']], 'Le indico cómo y cuándo retirar el resultado del PAP.'),
 (26, 'Concierta una nueva cita para ver los resultados', FF, 'cita', 0, {'cita': 1}, 'cita', 'Se acuerda una fecha para interpretar el resultado juntas y decidir el seguimiento (control anual, repetir el PAP, colposcopia o tratamiento).',
  [['nueva cita'], ['concierto una cita'], ['proxima cita'], ['turno'], ['para ver los resultados']], 'Concierto una nueva cita para ver los resultados.'),
 (27, 'Saluda y se despide', FF, 'paciente', 0, {'desp': 1}, 'hablar', 'El saludo final cierra la consulta con calidez.',
  [['me despido'], ['hasta luego'], ['hasta pronto'], ['chau'], ['gracias por venir']], 'Saludo y me despido de la paciente.'),
]
pasos = [dict(n=n, texto=tx, fase=fa, target=tg, critico=bool(cr), explica=ex, estado=es, claves=cl, frase=fr, fx=fx) for n, tx, fa, tg, cr, es, fx, ex, cl, fr in P]

def caso(i, nombre, edad, motivo, ant, cervix, parto, pared, vulva, vista_txt, ext_txt, h_ant, h_ext, h_cuello, h_vagina, h_utero, h_preg, extra):
    return dict(id=i, nombre=nombre, sexo='F', edad=edad, motivo=motivo, indicacion='Examen ginecológico con toma de PAP y tacto bimanual.', antecedentes=ant, alergia=None, cervix=cervix, parto=parto, pared=pared, vulva=vulva, vista_txt=vista_txt, ext_txt=ext_txt,
                h_ant=h_ant, h_ext=h_ext, h_cuello=h_cuello, h_vagina=h_vagina, h_utero=h_utero, h_preg=h_preg, h_pap='El resultado del PAP está en 20 días en el laboratorio del hospital.', extra=extra)
casos = [
 caso('c1', 'Agustina C.', 22, 'Control ginecológico de rutina; es su primer PAP.', 'Nuligesta. Sin antecedentes patológicos. Sin alergias conocidas.', 'normal', 'nulipara', 'normal', 'normal',
      'Cuello rosado, simétrico, con orificio externo puntiforme y moco claro.', 'Genitales externos sin lesiones.',
      'La paciente refiere ciclos regulares, sin flujo anormal, sin ITS y sin PAP previos.', 'Vulva de aspecto normal, sin lesiones, flujo ni tumoraciones.', 'Cuello de aspecto normal, rosado, orificio externo puntiforme y moco claro.', 'Paredes vaginales rosadas con rugosidades normales.', 'Útero en anteversoflexión, de tamaño normal, móvil e indoloro; anexos no palpables; fondos de saco libres.', 'La paciente pregunta: «¿Me va a doler? ¿Con qué frecuencia me tengo que hacer el PAP?».', ['Primer PAP']),
 caso('c2', 'Laura B.', 35, 'Control anual y flujo abundante.', 'G3P3. Sin patologías. Sin alergias conocidas.', 'ectropion', 'multipara', 'normal', 'normal',
      'Cuello con ectropión: zona roja alrededor del orificio, orificio en hendidura.', 'Genitales externos sin lesiones.',
      'Refiere flujo transparente abundante sin picazón, con sinusorragia ocasional. Último PAP hace 2 años, normal.', 'Vulva sin lesiones; flujo claro.', 'Cuello con ectropión (ectopia) en torno al orificio externo en hendidura, sin lesiones sospechosas.', 'Paredes vaginales normales; flujo transparente.', 'Útero en anteversoflexión, de tamaño normal, móvil e indoloro; anexos no palpables.', 'La paciente pregunta: «¿Esa zona roja es grave? ¿Por qué sangro después de las relaciones?».', ['Ectropión']),
 caso('c3', 'Romina F.', 26, 'Dolor bajo, flujo amarillento y mal olor.', 'Nuligesta. Clamidia tratada hace 2 años. Sin alergias conocidas.', 'cervicitis', 'nulipara', 'normal', 'leucorrea',
      'Cuello eritematoso con moco-pus amarillo que sale del orificio.', 'Flujo amarillento en el introito.',
      'Refiere dolor abdominal bajo, flujo amarillento maloliente, dispareunia y fiebre de 38 °C; varias parejas sin preservativo.', 'Flujo amarillento en el introito; sin lesiones.', 'Cuello eritematoso, friable al contacto, con moco-pus saliendo del orificio: cervicitis mucopurulenta.', 'Flujo amarillento abundante en las paredes.', 'Útero de tamaño normal, doloroso a la movilización; dolor en ambos anexos; signo de Chandelier positivo; sospecha de enfermedad pélvica inflamatoria.', 'La paciente pregunta: «¿Es una infección? ¿Se la puede contagiar mi pareja?».', ['Cervicitis / EPI']),
 caso('c4', 'Susana P.', 46, 'Sangrados irregulares entre menstruaciones.', 'G2P2. Miomatosis. Sin alergias conocidas.', 'polipo', 'multipara', 'normal', 'normal',
      'Pólipo rosado que asoma por el orificio cervical.', 'Genitales externos sin lesiones.',
      'Refiere metrorragia entre menstruaciones y sinusorragia desde hace 3 meses. Último PAP hace 3 años.', 'Vulva sin lesiones; leve sangrado en el introito.', 'Pólipo endocervical rosado, pediculado, que asoma por el orificio externo.', 'Paredes vaginales normales; sangre escasa.', 'Útero aumentado de tamaño (como de 8 semanas), irregular y firme, móvil e indoloro; anexos no palpables.', 'La paciente pregunta: «¿Ese bulto puede ser cáncer? ¿Me lo tienen que sacar?».', ['Pólipo endocervical']),
 caso('c5', 'Marta R.', 62, 'Sequedad y dolor en las relaciones.', 'G4P4. Menopausia a los 50 años. Hipertensión. Sin alergias conocidas.', 'atrofia', 'multipara', 'atrofica', 'normal',
      'Cuello pequeño, pálido, con orificio puntiforme; paredes lisas y delgadas.', 'Atrofia vulvar: labios adelgazados y pálidos.',
      'Refiere sequedad vaginal, ardor y dispareunia. Nunca se hizo PAP en los últimos 10 años.', 'Atrofia vulvar: labios menores adelgazados y pálidos, introito estrecho.', 'Cuello pequeño y pálido, con orificio puntiforme; mucosa fina.', 'Paredes vaginales pálidas, lisas, sin rugosidades y friables (vaginitis atrófica).', 'Útero pequeño, firme y móvil; anexos no palpables; introducción dolorosa del examen por el introito estrecho.', 'La paciente pregunta: «¿Es normal que me duela? ¿Hay algo para la sequedad?».', ['Atrofia posmenopáusica']),
 caso('c6', 'Carolina V.', 31, 'Picazón intensa y flujo blanco.', 'G1P1. Sin patologías. Sin alergias conocidas.', 'normal', 'multipara', 'candidiasis', 'leucorrea',
      'Cuello rosado normal; placas blanquecinas adheridas a las paredes vaginales.', 'Flujo blanco grumoso y eritema vulvar.',
      'Refiere prurito intenso y flujo blanco como «queso blanco» desde hace 5 días, después de tomar antibióticos.', 'Eritema vulvar con flujo blanco grumoso, escoriaciones por rascado.', 'Cuello de aspecto normal, rodeado de flujo blanco grumoso.', 'Placas blancas adheridas a las paredes vaginales: candidiasis vulvovaginal.', 'Útero de tamaño normal, móvil e indoloro; anexos no palpables.', 'La paciente pregunta: «¿Es una infección de transmisión sexual? ¿Puede volver?».', ['Candidiasis']),
 caso('c7', 'Beatriz M.', 40, 'Sangrado con las relaciones sexuales.', 'G3P3. Fuma 15 cigarrillos por día. Sin controles hace 6 años. Sin alergias conocidas.', 'lesion', 'multipara', 'normal', 'normal',
      'Lesión irregular, friable, que sangra al contacto.', 'Genitales externos sin lesiones.',
      'Refiere sinusorragia y flujo sanguinolento desde hace 2 meses. Nunca se hizo un PAP desde hace 6 años; inicio precoz de las relaciones.', 'Vulva sin lesiones.', 'Lesión exofítica irregular y friable en el labio anterior del cuello, que sangra al contacto: sospechosa de neoplasia.', 'Paredes vaginales normales; sangre escasa.', 'Útero de tamaño normal; cuello duro e indurado, con parametrios sin infiltrar; anexos no palpables.', 'La paciente pregunta: «¿Qué es esa herida? ¿Es cáncer?».', ['Lesión sospechosa del cuello']),
]
dists = [
 dd('d1', 'Lubrica el espéculo con gel o vaselina antes de introducirlo', 1, 'Es criterio de desaprobación: los lubricantes alteran las células y vuelven inservible el PAP; el espéculo se humedece solo con agua tibia o suero.', 'especulo', [['con gel'], ['con vaselina'], ['lubrico el especulo'], ['lubricante']]),
 dd('d2', 'Realiza el tacto vaginal antes de la toma de PAP', 1, 'Es criterio de desaprobación: el tacto previo contamina el cuello con lubricante y altera la muestra; el PAP se toma primero.', 'dedos', [['tacto antes del pap'], ['tacto antes de la toma'], ['primero el tacto'], ['antes de la citologia el tacto']]),
 dd('d3', 'Introduce el espéculo con las valvas abiertas', 1, 'Es criterio de desaprobación: se introduce cerrado, para no lastimar la mucosa ni el meato uretral.', 'especulo', [['valvas abiertas'], ['especulo abierto'], ['con el especulo abierto']]),
 dd('d4', 'Rota el espéculo en sentido antihorario', 0, 'La guía indica rotarlo 90° en sentido de las agujas del reloj a medida que se introduce.', 'especulo', [['antihorario'], ['sentido contrario a las agujas'], ['contrario a las agujas']]),
 dd('d5', 'Toma primero el endocérvix y luego el exocérvix', 1, 'Es criterio de desaprobación: se toma primero el exocérvix con la espátula y después el endocérvix con el citobrush.', 'espatula', [['primero el endocervix'], ['endocervix y luego el exocervix'], ['endocervix antes']]),
 dd('d6', 'No fija las muestras o las deja secar al aire', 1, 'Es criterio de desaprobación: el secado al aire altera las células y el PAP no se puede interpretar; se fija inmediatamente.', 'fijador', [['no fijo'], ['sin fijar'], ['dejo secar'], ['secar al aire'], ['omito el fijador']]),
 dd('d7', 'Retira el espéculo abierto', 1, 'Es criterio de desaprobación: se lo cierra antes de retirarlo para no lastimar a la paciente.', 'especulo', [['retiro el especulo abierto'], ['con las valvas abiertas'], ['sin cerrarlo']]),
 dd('d8', 'No explica el procedimiento antes de comenzar', 1, 'Es criterio de desaprobación: informar es parte del consentimiento y reduce la ansiedad y la contractura.', 'paciente', [['sin explicar'], ['no le explico'], ['sin informar'], ['no informo']]),
 dd('d9', 'No resguarda la intimidad de la paciente', 1, 'Es criterio de desaprobación: se la cubre con una sábana y solo se descubre la zona del examen.', 'sabana', [['sin cubrirla'], ['no resguardo'], ['sin sabana'], ['no la cubro']]),
 dd('d10', 'Realiza el examen sin luz o sin guantes', 1, 'Es criterio de desaprobación: los guantes protegen a ambos y sin luz no se puede ver el cuello.', 'guantes', [['sin guantes'], ['sin luz'], ['sin la lampara'], ['no uso guantes']]),
 dd('d11', 'Fuerza el espéculo ante la resistencia o el dolor de la paciente', 1, 'Es criterio de desaprobación: ante dolor o resistencia se detiene, se tranquiliza a la paciente y se cambia el tamaño o el ángulo.', 'especulo', [['fuerzo el especulo'], ['empujo con fuerza'], ['sin importar el dolor'], ['con fuerza el especulo']]),
 dd('d12', 'Toma la muestra con la paciente menstruando o con flujo sanguinolento abundante sin avisar ni reprogramar', 0, 'El PAP se toma idealmente fuera de la menstruación y 48 horas después de relaciones, duchas o óvulos.', 'paciente', [['durante la menstruacion'], ['menstruando'], ['sin importar el sangrado']]),
 dd('d13', 'No descarta el material ni se quita los guantes', 0, 'El material contaminado se descarta en la bolsa roja y se hace higiene de manos.', 'residuos', [['no descarto'], ['dejo el especulo'], ['sin descartar']]),
]
QS = [
 ('¿Cuál es la posición de la paciente para el examen con espéculo?', ['Ginecológica (litotomía): decúbito dorsal con rodillas flexionadas y muslos separados', 'Decúbito ventral', 'Sentada', 'Decúbito lateral derecho'], 0, 'La posición ginecológica expone el introito y permite introducir el espéculo.'),
 ('¿Cómo se introduce el espéculo?', ['Cerrado, apoyado sobre la horquilla, rotándolo 90° en sentido horario al avanzar', 'Abierto y de golpe', 'Con gel y sin rotarlo', 'De arriba hacia abajo en sentido vertical'], 0, 'Se introduce cerrado y se rota 90° para que las valvas queden arriba y abajo.'),
 ('¿Con qué se humedece el espéculo para tomar un PAP?', ['Con agua tibia o suero fisiológico', 'Con gel lubricante', 'Con vaselina', 'Con lidocaína en gel'], 0, 'Los lubricantes alteran las células: se usa agua tibia o suero.'),
 ('¿Con qué instrumento se toma el exocérvix?', ['Espátula de Ayre', 'Citobrush', 'Hisopo de algodón', 'Pinza de Pozzi'], 0, 'La espátula de Ayre se gira 360° apoyada sobre el exocérvix.'),
 ('¿Con qué instrumento se toma el endocérvix?', ['Citobrush (cepillo endocervical)', 'Espátula de Ayre', 'Histerómetro', 'Hisopo'], 0, 'El citobrush se introduce en el canal y se gira un cuarto a media vuelta.'),
 ('¿Qué orden se respeta en la toma de las muestras?', ['Primero el exocérvix y luego el endocérvix', 'Primero el endocérvix', 'Las dos a la vez', 'No importa'], 0, 'La guía indica espátula de Ayre y luego citobrush.'),
 ('¿Cuándo se fijan los extendidos?', ['Inmediatamente, con spray fijador', 'Después de media hora', 'No se fijan', 'Al día siguiente'], 0, 'El secado al aire destruye la morfología celular.'),
 ('¿Por qué se toma el PAP antes del tacto bimanual?', ['Para no contaminar el cuello con lubricante ni alterar la muestra', 'Porque duele menos', 'Es indistinto', 'Para ahorrar tiempo'], 0, 'El tacto se hace después, con lubricante, y puede alterar la citología.'),
 ('En el tacto bimanual, ¿qué hace la mano libre?', ['Se apoya sobre el hipogastrio y las fosas ilíacas y presiona hacia los dedos vaginales', 'Sostiene el espéculo', 'Abre la vulva', 'Descansa a un costado'], 0, 'Permite palpar el útero y los anexos entre ambas manos.'),
 ('¿Qué orificio externo tiene el cuello de una nulípara?', ['Puntiforme (redondeado)', 'En hendidura transversal', 'No tiene', 'Siempre abierto'], 0, 'En la multípara el orificio es una hendidura transversal.'),
 ('¿Qué indica un cuello friable que sangra al contacto?', ['Sospecha de lesión neoplásica o cervicitis: requiere colposcopia', 'Es normal', 'Un embarazo', 'Menopausia'], 0, 'Debe derivarse a colposcopia y biopsia dirigida.'),
 ('¿Cada cuánto se recomienda el control ginecológico con PAP?', ['Una vez al año (la guía de la cátedra)', 'Cada 10 años', 'Solo si hay síntomas', 'Una sola vez'], 0, 'La guía de la cátedra recomienda un control anual.'),
]
fund = [dict(q=q, o=o, c=c, e=e) for q, o, c, e in QS]
mach = {'perlas': [
 {'t': 'Antes del examen', 'x': 'Saludá, sentá a la paciente y a su familiar, interrogá antecedentes ginecológicos, informá el procedimiento, indicá la posición ginecológica y resguardá su intimidad.'},
 {'t': 'Genitales externos', 'x': 'Guantes y luz. Inspeccioná monte de Venus, labios, clítoris, meato, introito y horquilla. Entreabrí la vulva con índice y pulgar de la mano hábil.'},
 {'t': 'Espéculo', 'x': 'Cerrado, articulación hacia abajo, apoyado en la horquilla, inclinado a la izquierda, rotando 90° en sentido horario; separá las valvas con el pulgar sobre la valva superior; ubicá el cuello. Sin gel.'},
 {'t': 'PAP', 'x': 'Primero exocérvix con espátula de Ayre (girar 360°), luego endocérvix con citobrush; extendé cada muestra en un portaobjetos y fijá con spray enseguida.'},
 {'t': 'Tacto bimanual', 'x': 'Después del PAP: medio sobre la horquilla hacia el sacro, luego el índice; recorré la vagina; la mano libre en hipogastrio y fosas ilíacas. Retirá suave.'},
 {'t': 'Cierre', 'x': 'Descartá guantes y material, avisá que terminó, escuchá preguntas, indicá cómo retirar el PAP, concertá nueva cita y despedite.'}],
 'por_paso': {'10': 'Cerrado, 90° horario, sin gel.', '13': 'Exocérvix: espátula de Ayre, 360°.', '14': 'Endocérvix: citobrush.', '15': 'Fijar de inmediato.', '19': 'Después del PAP, nunca antes.'}}
CRIT = dict(criterios_texto='La lista de cotejo no define criterios de desaprobación automática; el simulador califica la bioseguridad y la intimidad, la técnica de introducción del espéculo, la toma y la fijación de las muestras del PAP y el tacto bimanual (propuesto, a validar).',
 criterios=[dict(ico='🛡️', titulo='Información, intimidad y bioseguridad', pasos=[4, 6, 7]), dict(ico='🔬', titulo='Introducción del espéculo y ubicación del cuello', pasos=[10, 11, 12, 16]), dict(ico='🧫', titulo='Toma del PAP: exocérvix, endocérvix y fijación', pasos=[13, 14, 15]), dict(ico='🖐️', titulo='Tacto vaginal bimanual', pasos=[19, 20]), dict(ico='🗑️', titulo='Descarte de material y guantes', pasos=[22])],
 final_criticos='la información e intimidad, la técnica del espéculo, la toma y fijación del PAP y el tacto bimanual')
ALG = dict(titulo='Interpretación del cuello uterino', boton_titulo='Ver los aspectos del cuello', boton_sub='Normal, ectropión, cervicitis, pólipo, atrofia, lesión', aviso='los aspectos del cuello', flecha='▼ Aspecto del cuello en la vista especular', flecha_final='▼ Conducta', pie='Lesión sospechosa, friable o sangrante: colposcopia.',
 comun=[dict(t='Cuello ubicado', x='Color, tamaño, orificio, secreciones y lesiones.', flag='cuello'), dict(t='Muestras tomadas', x='Exocérvix + endocérvix, fijadas.', flag='fija')],
 columnas=[dict(titulo='Normal / ectropión', cls='nd', nodos=[dict(t='Normal', x='Rosado, orificio puntiforme (nulípara) o en hendidura (multípara), moco claro.', flag='cuello'), dict(t='Ectropión (ectopia)', x='Zona roja alrededor del orificio, frecuente en multíparas y anticonceptivas.', flag='cuello')]),
  dict(titulo='Infección', cls='fv', nodos=[dict(t='Cervicitis', x='Eritematoso, friable, moco-pus: tratar la ITS y estudiar EPI.', flag='cuello'), dict(t='Candidiasis', x='Placas blancas en las paredes: antifúngico.', flag='cuello')]),
  dict(titulo='Lesiones', cls='fv', nodos=[dict(t='Pólipo endocervical', x='Estudiar el sangrado; polipectomía.', flag='cuello'), dict(t='Lesión friable', x='Colposcopia y biopsia dirigida.', flag='cuello'), dict(t='Atrofia', x='Paredes pálidas y lisas: estrógenos locales.', flag='cuello')])],
 final=[dict(t='Resultado del PAP', x='Se retira en 15-30 días y se interpreta en una nueva cita.', flag='res')])
EL = {'paciente': ('Paciente', 'Se la saluda, se le explica el examen, se resguarda su intimidad y se la despide.'), 'consultorio': ('Consultorio', 'Sillas para la paciente y el acompañante.'), 'camilla': ('Camilla ginecológica', 'Posición ginecológica con estribos.'), 'sabana': ('Sábana', 'Resguarda la intimidad.'), 'guantes': ('Guantes y luz', 'Guantes de látex y lámpara de pie.'),
  'vulva': ('Genitales externos', 'Se inspeccionan y se entreabre la vulva.'), 'especulo': ('Espéculo', 'Se introduce cerrado y se rota 90°.'), 'cuello': ('Cuello uterino', 'Se ubica y se describe.'), 'espatula': ('Espátula de Ayre', 'Toma del exocérvix.'), 'citobrush': ('Citobrush', 'Toma del endocérvix.'), 'fijador': ('Fijador en spray', 'Fija los extendidos.'),
  'dedos': ('Dedos examinadores', 'Medio e índice de la mano hábil.'), 'hipogastrio': ('Hipogastrio', 'Donde se apoya la mano libre.'), 'residuos': ('Bolsa roja', 'Descarte del material.'), 'resultado': ('Resultado del PAP', 'Cómo y cuándo retirarlo.'), 'cita': ('Nueva cita', 'Para ver los resultados.')}
EX = dict(id='exgin', area='sim', titulo='Examen ginecológico, PAP y tacto bimanual', icono='🔬',
 resumen='Recorrido virtual del examen ginecológico con 27 pasos de la lista de cotejo: genitales externos, espéculo, toma de citología cervical (exocérvix y endocérvix), fijación y tacto vaginal bimanual, con vista especular del cuello.',
 umbral=60, fuente='Lista de cotejo: Examen ginecológico, toma de citología cervical y tacto vaginal bimanual (27 ítems)',
 elementos={k: dict(nombre=v[0], desc=v[1], pasos=[p['n'] for p in pasos if p['target'] == k]) for k, v in EL.items()}, distractores=dists, casos=casos, fundamentos=fund, voz=True, algoritmo=ALG,
 hallazgo_pasos={'3': 'h_ant', '8': 'h_ext', '12': 'h_cuello', '19': 'h_vagina', '20': 'h_utero', '24': 'h_preg', '25': 'h_pap'}, hallazgo_rotulos={'3': '🗣 Paciente:', '8': '👁️ Observás:', '12': '👁️ Observás:', '19': '🖐️ Palpás:', '20': '🖐️ Palpás:', '24': '🗣 Paciente:', '25': '📋'}, hallazgo_voz={'3': 'f', '24': 'f'},
 machete=mach, examen=dict(tiempos=[5, 10, 15, 30], penalizacion_incorrecta=3, penalizacion_repetida=1),
 visor='data/acreditaciones/sim/exgin_modelo.json', peso_modelo='2 a 3 MB', instrumental='data/acreditaciones/sim/instrumental_exgin.json', mesa_pasos=[], pasos=pasos)
EX.update(CRIT); W(OUT + 'exgin.json', EX)
def it(id, grupo, nombre, detalle, correcto, critico, desc, ficha, **kw):
    o = dict(id=id, grupo=grupo, nombre=nombre, detalle=detalle, img=f'assets/instrumental/{id}.svg', correcto=correcto, critico=critico, descripcion=desc, ficha=ficha); o.update(kw); return o
items = [
 it('guantes_ns', 'prot', 'Guantes de látex', 'Caja de guantes', True, True, 'Barrera de protección para la paciente y para el examinador.', [['Material', 'Látex']], falta='Faltan los guantes de látex.'),
 it('lampara_pie', 'prot', 'Lámpara de pie', 'Luz orientable', True, True, 'Ilumina el introito y el cuello para verlos bien.', [['Tipo', 'De pie, orientable']], falta='Falta la lámpara de pie para ver el cuello.'),
 it('bata_paciente', 'prot', 'Bata de la paciente', 'Descartable', True, False, 'Para que la paciente se libere de la ropa resguardando su intimidad.', [['Uso', 'Intimidad']]),
 it('sabana_campo', 'prot', 'Sábana o campo', 'Para cubrir', True, True, 'Cubre a la paciente y descubre solo la zona del examen.', [['Uso', 'Resguardo de la intimidad']], falta='Falta la sábana para cubrir a la paciente.'),
 it('alcohol_gel', 'prot', 'Alcohol en gel', 'Higiene de manos', True, False, 'Higiene de manos antes y después del examen.', [['Uso', 'Higiene de manos']]),
 it('camilla_gin', 'prot', 'Camilla ginecológica', 'Con estribos', True, True, 'Para la posición ginecológica.', [['Uso', 'Posición ginecológica']], falta='Falta la camilla con estribos.'),
 it('especulo', 'toma', 'Espéculo descartable', 'Tamaño mediano', True, True, 'Instrumento bivalvo que separa las paredes vaginales y deja ver el cuello.', [['Tipo', 'Bivalvo descartable'], ['Tamaño', 'Mediano']], falta='Falta el espéculo vaginal.'),
 it('espatula_ayre', 'toma', 'Espátula de Ayre', 'Madera descartable', True, True, 'Para tomar la muestra del exocérvix.', [['Uso', 'Exocérvix']], falta='Falta la espátula de Ayre.'),
 it('citobrush', 'toma', 'Citobrush', 'Cepillo endocervical', True, True, 'Para tomar la muestra del endocérvix.', [['Uso', 'Endocérvix']], falta='Falta el citobrush.'),
 it('portaobjetos', 'toma', 'Portaobjetos', '2 unidades, rotulables', True, True, 'Donde se extiende cada muestra.', [['Cantidad', '2']], falta='Faltan los portaobjetos.'),
 it('fijador_spray', 'toma', 'Fijador en spray', 'Citológico', True, True, 'Fija los extendidos inmediatamente.', [['Uso', 'Fijación']], falta='Falta el fijador en spray.'),
 it('orden_pap', 'toma', 'Orden de PAP', 'Solicitud de estudio', True, False, 'Acompaña los portaobjetos al laboratorio.', [['Documento', 'Orden']]),
 it('bolsa_roja', 'prot', 'Bolsa roja de residuos', 'Patogénicos', True, False, 'Para el espéculo y los guantes descartados.', [['Color', 'Rojo']]),
 it('gel_lubricante', 'otros', 'Gel lubricante', 'Hidrosoluble', False, False, 'Lubricante.', [['Uso', 'Lubricación']], feedback='Los lubricantes alteran las células y vuelven inservible el PAP; el espéculo se humedece con agua tibia.'),
 it('histerometro', 'otros', 'Histerómetro', 'Metálico', False, False, 'Mide la cavidad uterina.', [['Uso', 'Cavidad uterina']], feedback='No forma parte del PAP ni del examen de rutina.'),
 it('pinza_pozzi', 'otros', 'Pinza de Pozzi', 'Metálica', False, False, 'Pinza de tracción del cuello.', [['Uso', 'Tracción']], feedback='No se usa en un PAP de rutina.'),
 it('colposcopio', 'otros', 'Colposcopio', 'Equipo óptico', False, False, 'Magnifica el cuello.', [['Uso', 'Colposcopia']], feedback='Se indica luego, si el PAP o el examen son anormales.'),
 it('hisopo_algodon', 'otros', 'Hisopo de algodón', 'Estéril', False, False, 'Toma de cultivos.', [['Uso', 'Cultivo']], feedback='No reemplaza a la espátula ni al citobrush para el PAP.'),
]
INS = dict(id='exgin', titulo='Consultorio de ginecología · Examen y toma de PAP', consigna='Reuní lo que hace falta para el examen ginecológico y la toma de PAP: protección, espéculo, instrumentos de toma, portaobjetos y fijador. Pasá el cursor (o tocá) cada insumo para inspeccionarlo; arrastralo a la bandeja o hacé clic para agregarlo.',
 caso_sub='examen ginecológico con toma de PAP', indicacion_def='Examen ginecológico con toma de PAP y tacto bimanual.', mision=['qué hace falta para el examen y la toma de las muestras;', 'qué insumos no corresponden al PAP.'], demo_caso='Primero se lee el caso: el motivo orienta lo que se espera encontrar.',
 grupos=[dict(id='prot', titulo='Protección y confort'), dict(id='toma', titulo='Examen y toma de PAP'), dict(id='otros', titulo='Otros insumos')], items=items, bandeja_img='assets/instrumental/bandeja.svg')
W(OUT + 'instrumental_exgin.json', INS)
M = J('data/acreditaciones/siam/sv_modelo.json')
glb = lambda id, carpeta, f, capa, color, op, hs, nom, peso, **kw: dict(id=id, tipo='glb', src=f'assets/anatomia/{carpeta}/{f}.glb', escala=100, rot=[0, 0, 0], pos=[0, 0, 0], capa=capa, color=color, opacidad=op, hs=hs, nombre=nom, peso=peso, **kw)
piezas = [glb('piel', 'sim', 'torso_f', 'piel', '#d8a387', 0.34, None, 'Paciente', 1255052, piel_real=True), glb('pelvis', 'hra', 'pelvis_f', 'huesos', '#e8e1cf', 0.55, 'pelvis', 'Pelvis ósea', 120000),
          glb('utero', 'hra', 'uterus_f', 'organos', '#ff6fb5', 0.8, 'utero', 'Útero y cuello', 150000), glb('ovarios', 'sim', 'ovarios', 'organos', '#f9a8d4', 0.95, 'ovarios', 'Ovarios', 3044), glb('trompas', 'sim', 'trompas', 'organos', '#fda4af', 0.9, 'trompas', 'Trompas', 24696), glb('vejiga', 'hra', 'bladder_f', 'organos', '#ffc21a', 0.6, 'vejiga', 'Vejiga', 100000)]
VAR = dict(origen=[-1.3, 2, -3], corte_x=-1.3, rotacion=[0, 0, 0], piezas=piezas, procedurales={},
  gin=dict(introito=[-1.3, -3.0, -1.2], os=[-1.1, 0.9, -7.2], p1=[-1.3, -1.6, -3.0], p2=[-1.2, -0.2, -5.1], radio=1.5, hipogastrio=[-1.3, 7.6, 7.0]),
  pines=dict(cuello=[-1.1, 1.3, -7.0], introito=[-1.3, -3.0, -1.2], utero=[-1.4, 4.0, -3.5], ovarios=[6, 6.2, -4.0]),
  camara=dict(lat=[-60, 2, 0], fro=[0, 2, 60], sup=[-1.3, 60, 0.01], objetivo=[0, 0, -7], ini=[-26, 2, 6]), etiquetas=dict(cuello=[-100, -50], introito=[-110, 40], utero=[-120, -90], ovarios=[100, -30]))
G = dict(M['general']); G['camara'] = dict(M['general']['camara'], foco=22, min=8, max=100); G['corte_inicial'] = True
IM = dict(general=G, overlay_html='', tarjetas=dict(mesa=dict(titulo='🧰 Material', id='mesa', items=[['especulo', '🔧', 'Espéculo', ''], ['espatula', '🪵', 'Espátula', 'de Ayre'], ['citobrush', '🪥', 'Citobrush', ''], ['fijador', '🧴', 'Fijador', 'en spray'], ['guantes', '🧤', 'Guantes', 'y luz']]), entorno=dict(titulo='🏥 Consultorio', items=[['paciente', '🧍‍♀️', 'Paciente', ''], ['camilla', '🛏️', 'Camilla', 'ginecológica'], ['sabana', '🧻', 'Sábana', ''], ['residuos', '🗑️', 'Bolsa', 'roja']])),
  chips=[['guantes', 'Guantes y luz'], ['vulva', 'Genitales externos'], ['esp', 'Espéculo'], ['valvas', 'Valvas abiertas'], ['ayre', 'Exocérvix'], ['cito', 'Endocérvix'], ['fija', 'Fijado'], ['bimd', 'Tacto bimanual'], ['desc', 'Descarte']],
  usables=['especulo', 'espatula', 'citobrush', 'fijador', 'guantes', 'paciente', 'camilla', 'sabana', 'residuos'],
  pines=[dict(id='cuello', label='Cuello uterino', capa='organos'), dict(id='introito', label='Introito vaginal', capa='piel', externo=True), dict(id='utero', label='Útero', capa='organos'), dict(id='ovarios', label='Ovarios', capa='organos')],
  instrumentos=[dict(id='gin', tipo='gin', clases=dict(vulva='s-vulva', abre='s-abre', esp='s-esp', valvas='s-valvas', cuello='s-cuello', ayre='s-ayre', cito='s-cito', fija='s-fija', cierra='s-cierra', retira='s-retira', abre2='s-abre2', bimd='s-bimd', bima='s-bima', bimr='s-bimr'))], M=VAR, F=VAR)
W(OUT + 'exgin_modelo.json', IM)
print('ok exgin', len(pasos), len(casos))
